name = "Ian Emnace"
downloads-dir = "/home/ian/Downloads"
notify-query = "not seen"

[Main]
default = true
email = "igemnace@gmail.com"
notify-cmd = "mail-notify"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "igemnace@gmail.com"
imap-passwd-cmd = "pass show email/google/app-password/igemnace@gmail.com/himalaya"
pgp-encrypt-cmd = "gpg -o - -eqar"
watch-cmds = ["mbsync Main"]

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "igemnace@gmail.com"
smtp-passwd-cmd = "pass show email/google/app-password/igemnace@gmail.com/himalaya"
pgp-decrypt-cmd = "gpg -dq"

[Gaming]
email = "29forte95@gmail.com"
notify-cmd = "mail-notify"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "29forte95@gmail.com"
imap-passwd-cmd = "pass show email/google/app-password/29forte95@gmail.com/himalaya"
pgp-encrypt-cmd = "gpg -o - -eqar"
watch-cmds = ["mbsync Gaming"]

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "29forte95@gmail.com"
smtp-passwd-cmd = "pass show email/google/app-password/29forte95@gmail.com/himalaya"
pgp-decrypt-cmd = "gpg -dq"
