#!/usr/bin/env bash

usage() {
  cat << EOF
Usage: rsync-watch SRC DEST

rsync-watch will automatically detect changes to files in the SRC directory
and rsync them to the DEST directory.
EOF
}

if [[ -z $1 ]] || [[ -z $2 ]]; then
  usage

  exit 0
fi

inotifywait -rme modify --format '%w%f' "$1" | while read -r filename; do
  echo >&2 "Syncing ${filename##*/}..."

  rsync "$filename" "$2/$filename"

  echo >&2 "Done."
done

# clean up
unset -f usage
